### ISSUE TITLE
Add the default realm to the Fedora CoreOS ignition file

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/nessus-actions#29]

**Comment by tdiesler** [comment]
```
storage:
  trees:
    - local: tls
      path: /var/home/core/tls
  files:
    - path: /var/home/core/keycloak/myrealm.json
      contents:
        source: https://raw.githubusercontent.com/tdiesler/nessus-actions/master/docs/myrealm.json
      mode: 0644
```
